### ISSUE TITLE
Implement Previous button on the Messages page

### ISSUE THREAD

**Issue by agolosen** [provectus/kafka-ui#1440] opened 2022-01-20 13:29 UTC
### Is your proposal related to a problem?

(Write your answer here.)
There is only the button Next on the Messages page. If you navigate to the next page there are no options to go back.
### Describe the solution you'd like

Please add the button 'Previous' that lead to the previous page of Messages.
(Describe your proposed solution here.)

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

![image](https://user-images.githubusercontent.com/92585878/150347914-0013e5d9-6db7-4603-9a5a-8dbd060d9447.png)

(Write your answer here.)

**Comment by Haarolean** [comment] 2022-01-20 13:30
Duplicate of #721

**Closed by Haarolean** 2022-01-20 13:30 UTC
Labels: type/enhancement, status/triage
