### ISSUE TITLE
button "+ Add Custom Parameter" return 404

### ISSUE THREAD

**Issue by fisherwei** [provectus/kafka-ui#3605] opened 2023-04-03 02:20 UTC
**Describe the bug**
button "+ Add Custom Parameter" return 404

**Expected behavior**
a parameter list?

**Set up**
kafka-ui: v0.6.0 and v0.6.1
kafka: 2.2

**Steps to Reproduce**
choose an exist topic
enter "edit settings" page
click "+ Add Custom Parameter" button
i got a 404 page

**Additional context**

**Comment by Haarolean** [comment] 2023-04-03 04:29
Hi, could you please share a screenshot of 404 you've got?

**Comment by fisherwei** [comment] 2023-04-03 12:29
> Hi, could you please share a screenshot of 404 you've got?

![BXEl2h3MPi](https://user-images.githubusercontent.com/214470/229509785-caf8d7cc-9866-4750-b893-86bb855db3d8.png)

**Comment by Haarolean** [comment] 2023-04-12 17:08
Duplicate of #3554. To be resolved within #3661.

**Closed by Haarolean** 2023-04-12 17:08 UTC
Labels: type/bug, status/duplicate, scope/frontend
