### ISSUE TITLE
In Message list Next button is not working properly

### ISSUE THREAD

**Issue by devteam-tb** [provectus/kafka-ui#4137] opened 2023-08-18 07:48 UTC
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

I have setup the Kafka-ui using  `provectuslabs/kafka-ui:latest` this image,
In the Message list I have 203 messages I can see only 99 messages, if I click the Next button it will get loading and show the same 99 messages, so the Next button is not working properly. Can you please quickly fix this issue? we are using in live
I have attached the image for your reference
1. Initial stage
![image](https://github.com/provectus/kafka-ui/assets/128605174/fe7d7a72-b0d3-4ec1-8292-4b5be43d64ab)
2. Once Click the next button
![image](https://github.com/provectus/kafka-ui/assets/128605174/bc574b45-4374-4204-942a-9d7424485d78)

### Expected behavior

I want to see the next data in message list

### Your installation details

I have integrated with docker image

### Steps to reproduce

1. Create lots of queue jobs more than 150 or 100.
2. See the messages in dashboard
3. Click the Next button, it shown same data instead of next data

**Comment by Haarolean** [comment] 2023-08-18 08:07
Hi, this is a duplicate of #3129. Should be fixed within #3504
Please follow the original issue, cheers!

**Closed by Haarolean** 2023-08-18 08:07 UTC
Labels: type/bug, status/triage
