### ISSUE TITLE
Filtering by offset and timestamp is not functional

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2856] opened 2022-11-01 06:37 UTC
**Describe the bug**
Filtering by offset and timestamp is not functional within Topic/messages tab

**Set up**

https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Topic/Messages tab
2. Select value for "Seek type"
3. Enter the value for Offset/Timestamp
4. Press "Submit"

**Expected behavior**
Messages should be filtered by selected value

**Screenshots**

https://user-images.githubusercontent.com/104780608/199173776-0e590c68-5f98-49fe-bdd0-a16058b14155.mov

**Comment by th0ger** [comment] 2022-12-06 07:08
Possible duplicate of #2956

**Comment by armenuikafka** [comment] 2022-12-19 12:12
will be fixed with https://github.com/provectus/kafka-ui/pull/3057#pullrequestreview-1213387831

**Comment by Haarolean** [comment] 2022-12-19 18:46
#2624

**Closed by Haarolean** 2022-12-19 18:46 UTC
Labels: type/bug, status/duplicate, status/confirmed
