### ISSUE TITLE
Message viewer tab missing page navigation buttons, displays only 100 but shows 500 messages consumed.

### ISSUE THREAD

**Issue by nitin1677** [provectus/kafka-ui#2798] opened 2022-10-21 13:11 UTC
**Describe the bug**

Message viewer tab missing page navigation buttons
Select the topic.
Switch to messages tab (no filters).
Screen shows, 500 messages consumed
Data grid shows only 100 messages.

URL:
http://<host>:8080/ui/clusters/<cluster-name>/all-topics/<topic-name>/messages?filterQueryType=STRING_CONTAINS&attempt=1&**limit=100**&seekDirection=FORWARD&keySerde=String&valueSerde=String&seekType=BEGINNING&seekTo=0%3A%3A31979786

Even if i change limit=100 to limit=500 in url, still shows 100 events only.
http://<host>:8080/ui/clusters/<cluster-name>/all-topics/<topic-name>/messages?filterQueryType=STRING_CONTAINS&attempt=1&**limit=500**&seekDirection=FORWARD&keySerde=String&valueSerde=String&seekType=BEGINNING&seekTo=0%3A%3A31979786

**Page navigation buttons are missing and unable to navigate pages for more events.**

**Set up**

**1. UI for Apache Kafka 10.14.2022 05:17:20 ( 2b5dd27 )**

**Steps to Reproduce**

1. 

**Expected behavior**

**Page navigation buttons should be added to navigate pages for events more than 100.**

**Screenshots**

**Additional context**

**Comment by Haarolean** [comment] 2022-10-25 20:26
Hey, thanks for the detailed report!

We've consumed 500 messages because it's the default polling limit, but displayed just 100 of them.
We know about the pagination regression (#2488), we'll take a look soon. 
Please let me know if you have any other questions.

Closing as a duplicate.

**Closed by Haarolean** 2022-10-25 20:26 UTC
Labels: type/bug, status/triage
