### ISSUE TITLE
cannot add new cluster

### ISSUE THREAD

**Issue by mprivoro** [provectus/kafka-ui#3918] opened 2023-06-08 14:06 UTC
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

i cannot add new cluster

### Your installation details

even when env. set as requested 
    environment:
      - DYNAMIC_CONFIG_ENABLED=true

### Steps to reproduce

even when env. set as requested 
    environment:
      - DYNAMIC_CONFIG_ENABLED=true

### Screenshots

![image](https://github.com/provectus/kafka-ui/assets/7849370/85b4be95-7b4b-46c2-867a-75ff118de553)

**Comment by Haarolean** [comment] 2023-06-09 16:40
Duplicate of #3835, fixed within #3862.
Please provide your setup details next time!

**Closed by Haarolean** 2023-06-09 16:40 UTC
Labels: type/bug, status/triage
