### ISSUE TITLE
Show inacitve consumers in the consumers group page

### ISSUE THREAD

**Issue by pavlospt** [provectus/kafka-ui#3867] opened 2023-05-25 14:42 UTC
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

Recently we stumbled upon cases when testing, where we needed to reset offsets for not active consumers, but those were not visible through the UI.

### Describe the feature you're interested in

We would like to be able to see the inactive consumers in the consumers list, in order to be able to reset offsets there as well.

### Describe alternatives you've considered

Kafka CLI was used in order to avoid this limitation.

### Version you're running

fdd9ad9 5/11/2023

**Comment by iliax** [comment] 2023-05-29 08:25
Hello @pavlospt, thank you for raising it. Unfortunately, I can't reproduce it - empty consumers are present on "Consumers" page with "Empty" state. 
Can you please add more details about your setup? Are you using ACL? Maybe target CG is not visible for kafka-ui user?

**Comment by pavlospt** [comment] 2023-05-29 08:34
We are not using ACLs, the Kafka cluster is on MSK and we are using IAM for the autentication part. Kafka UI as application, has all administrative permissions for actions on the cluster. Let me forward this to my colleagues, who initially spotted the issue, I may have failed to describe the issue properly!

**Comment by th3hunt** [comment] 2023-06-08 07:55
Hello all,

I think can shed some light on the problem. Imo whether it's an actual issue or a request for improvement is a matter of interpretation :)

So the use case here is to **reset the offset of a consumer for a particular topic**.

So I do the following

1. Open kafka-uo
2. Go to topic X
3. Click consumers tab
4. View the consumer group in STABLE state

Now, if you disconnect the actual running consumer group from Kafka and you refresh the page, 
the consumer group will no longer appear in the tab. This, I guess makes sense since now the 
consumer-group is not actively associated with the topic. Still, it feels like being lost for a moment.

Next, 

1. Lookup the consumer in the Consumers page
2. Find and click on the consumer three-dots and select `Reset offset`.
3. Instead of displaying the form to select the topic to reset the offset for, I am being presented with a blank screen.

**Possible workaround**

1. Visit the consumer while it's active
2. Click the three-dots and go to the `Reset offset` form
3. Select topic and partitions
4. Disconnect the consumers to bring the group in EMPTY state,
5. Click `Submit`

Still haven't made it work though, so I resorted to the CLI.

I hope the above helps.

Thank you 🙏

**Comment by iliax** [comment] 2023-06-12 13:29
Hello @th3hunt, thank you for providing full description.
From what I can see your consumer **has no committed offsets** before stop. Kafka-ui shows consumer group in topic's page if it has committed offsets OR it has alive members reading from it (even no offsets were committed).  

After the stop kafka will remember consumer group for some short period of time (and you will see it in Consumers list with Empty state).  But after that group will be completely forgotten since the only persistent notion of cg is committed offsets.   

Currently, "Reset offsets" functionality is designed in a way to **alter** already committed offsets of the CG (you chose from topics from which you already committed). 

We will definitely fix blank page behavior and think how to cover your case (within a separate ticket). 

Related: https://github.com/provectus/kafka-ui/issues/3932

**Closed by iliax** 2023-06-12 13:29 UTC
