### ISSUE TITLE
Not able to fetch Kafka details

### ISSUE THREAD

**Issue by usmanq8** [provectus/kafka-ui#2097] opened 2022-06-02 06:31 UTC
I am using **Kafka 0.9.x** version, i installed UI FOR KAFKA using Docker and then following directions to add bootstrap server using 
**host.docker.internal:9092** against **KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS** env. variable.
now on UI it connects but does not bring any details and throws exception.

`2022-06-02 06:29:35,420 INFO  [parallel-3] o.a.k.c.u.AppInfoParser: Kafka version: 2.8.0
2022-06-02 06:29:35,420 INFO  [parallel-3] o.a.k.c.u.AppInfoParser: Kafka commitId: ebb1d6e21cc92130
2022-06-02 06:29:35,420 INFO  [parallel-3] o.a.k.c.u.AppInfoParser: Kafka startTimeMs: 1654151375420
2022-06-02 06:29:38,386 INFO  [kafka-admin-client-thread | adminclient-3] o.a.k.c.a.i.AdminMetadataManager: [AdminClient clientId=adminclient-3] Metadata update failed
org.apache.kafka.common.errors.TimeoutException: Call(callName=fetchMetadata, deadlineMs=1654151378380, tries=1, nextAllowedTryMs=1654151378486) timed out at 1654151378386 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call. Call: fetchMetadata
2022-06-02 06:30:05,317 INFO  [kafka-admin-client-thread | adminclient-4] o.a.k.c.a.i.AdminMetadataManager: [AdminClient clientId=adminclient-4] Metadata update failed
org.apache.kafka.common.errors.TimeoutException: Call(callName=fetchMetadata, deadlineMs=1654151405286, tries=1, nextAllowedTryMs=1654151405417) timed out at 1654151405317 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call. Call: fetchMetadata
2022-06-02 06:30:05,422 INFO  [kafka-admin-client-thread | adminclient-17] o.a.k.c.a.i.AdminMetadataManager: [AdminClient clientId=adminclient-17] Metadata update failed
org.apache.kafka.common.errors.TimeoutException: Call(callName=fetchMetadata, deadlineMs=1654151405421, tries=1, nextAllowedTryMs=1654151405522) timed out at 1654151405422 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call. Call: fetchMetadata
2022-06-02 06:30:13,923 INFO  [kafka-admin-client-thread | adminclient-5] o.a.k.c.a.i.AdminMetadataManager: [AdminClient clientId=adminclient-5] Metadata update failed
org.apache.kafka.common.errors.TimeoutException: Call(callName=fetchMetadata, deadlineMs=1654150903650, tries=1, nextAllowedTryMs=1654151414023) timed out at 1654151413923 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: fetchMetadata
2022-06-02 06:30:35,424 INFO  [kafka-admin-client-thread | adminclient-17] o.a.k.c.a.i.AdminMetadataManager: [AdminClient clientId=adminclient-17] Metadata update failed
org.apache.kafka.common.errors.TimeoutException: Call(callName=fetchMetadata, deadlineMs=1654151435422, tries=1, nextAllowedTryMs=1654151435524) timed out at 1654151435424 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call. Call: fetchMetadata
2022-06-02 06:30:35,424 ERROR [parallel-3] c.p.k.u.s.MetricsService: Failed to collect cluster Default info
java.lang.IllegalStateException: Error while creating AdminClient for Cluster Default
at com.provectus.kafka.ui.service.AdminClientServiceImpl.lambda$createAdminClient$3(AdminClientServiceImpl.java:45)
at reactor.core.publisher.Mono.lambda$onErrorMap$31(Mono.java:3733)
at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:140)
at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:187)
at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: org.apache.kafka.common.errors.TimeoutException: Call(callName=listNodes, deadlineMs=1654151435421, tries=1, nextAllowedTryMs=1654151435522) timed out at 1654151435422 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: listNodes
2022-06-02 06:30:35,426 DEBUG [parallel-3] c.p.k.u.s.ClustersMetricsScheduler: Metrics updated for cluster: Default
2022-06-02 06:30:35,432 DEBUG [parallel-4] c.p.k.u.s.ClustersMetricsScheduler: Start getting metrics for kafkaCluster: Default
2022-06-02 06:30:35,436 INFO  [parallel-4] o.a.k.c.a.AdminClientConfig: AdminClientConfig values: `

**Comment by Haarolean** [comment] 2022-06-02 08:48
Hi, please provide the details on how you run the app: docker command/docker-compose

**Comment by usmanq8** [comment] 2022-06-02 08:52
> Hi, please provide the details on how you run the app: docker command/docker-compose

I am using Docker Desktop --> Kitematic and installed UIFORKAFKA and configured only above ENV. Var as mentioned. and tried to access it. It picks up Kafka as Default but cannot fetch META DETA at any level.

**Comment by Haarolean** [comment] 2022-06-02 08:53
How did you "install" the app? How do you run it? Please provide more info on that.

**Comment by usmanq8** [comment] 2022-06-02 09:23
Simply Thru KITEMATIC i can search an image, and CREATE, it gets me instance ready on Docker.
Then in its Settings i provide ENV. Variable as mentioned on UI FOR KAFKA. it picks up server but as said does not get META DATA
![1](https://user-images.githubusercontent.com/41000007/171599194-e0332d50-5669-4c65-93e7-40cf504a6e97.png)
![2](https://user-images.githubusercontent.com/41000007/171599205-98cdc725-e8c1-427d-8143-8598d52b5b3b.png)
![3](https://user-images.githubusercontent.com/41000007/171599210-8aba237a-cbfa-458c-ad3e-5fd5ba70ca9b.png)
![4](https://user-images.githubusercontent.com/41000007/171599213-6c9e8679-770b-4e6d-b8c5-8bde47fa22ab.png)
![5](https://user-images.githubusercontent.com/41000007/171599215-3f87fcdf-c86a-4db3-9ed6-33821957e60f.png)
.

**Comment by Haarolean** [comment] 2022-06-02 09:43
There's a chance that host.docker.internal might not work especially on linux. Could you try `172.17.0.1` instead? You can also verify that it's the right network/host. Also, don't forget that you have to adjust kafka's advertised listeners adding one with the corresponding host.

**Comment by usmanq8** [comment] 2022-06-02 09:49
172.17.0.1. is not valid, I am using Windows OS.

**Comment by Haarolean** [comment] 2022-06-02 09:53
Do this:
`docker exec -it kafka-ui sh`
and there do the following:
`ping host.docker.internal`
is it reachable?

**Comment by Haarolean** [comment] 2022-06-02 10:31
Run `ipconfig` on your host machine, check docker's network IPv4 address, it might be `10.0.75.1`

**Comment by usmanq8** [comment] 2022-06-02 13:45
Sorry i was pinging on wrong window it got pinged and address was 10.x.x.x.
so
`KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS =  10.x.x.x:9092`
`KAFKA_ADVERTISED_LISTENERS = PLAINTEXT://10.x.x.x:9092`

Modified kafka server.properties to have listener on above address too.

Below exception occurs after it:

`2022-06-02 13:44:11,172 INFO  [parallel-1] o.a.k.c.u.AppInfoParser: Kafka version: 2.8.0
2022-06-02 13:44:11,172 INFO  [parallel-1] o.a.k.c.u.AppInfoParser: Kafka commitId: ebb1d6e21cc92130
2022-06-02 13:44:11,172 INFO  [parallel-1] o.a.k.c.u.AppInfoParser: Kafka startTimeMs: 1654177451172
2022-06-02 13:44:12,828 WARN  [parallel-4] o.h.v.i.p.j.JavaBeanExecutable: HV000254: Missing parameter metadata for TopicColumnsToSortDTO(String, int, String), which declares implicit or synthetic parameters. Automatic resolution of generic type information for method parameters may yield incorrect results if multiple parameters have the same erasure. To solve this, compile your code with the '-parameters' flag.
2022-06-02 13:44:12,840 WARN  [parallel-4] o.h.v.i.p.j.JavaBeanExecutable: HV000254: Missing parameter metadata for SortOrderDTO(String, int, String), which declares implicit or synthetic parameters. Automatic resolution of generic type information for method parameters may yield incorrect results if multiple parameters have the same erasure. To solve this, compile your code with the '-parameters' flag.
2022-06-02 13:44:12,856 INFO  [parallel-4] o.a.k.c.a.AdminClientConfig: AdminClientConfig values: `

`2022-06-02 13:44:35,754 INFO  [parallel-1] o.a.k.c.u.AppInfoParser: Kafka version: 2.8.0
2022-06-02 13:44:35,755 INFO  [parallel-1] o.a.k.c.u.AppInfoParser: Kafka commitId: ebb1d6e21cc92130
2022-06-02 13:44:35,755 INFO  [parallel-1] o.a.k.c.u.AppInfoParser: Kafka startTimeMs: 1654177475754
2022-06-02 13:44:41,176 INFO  [kafka-admin-client-thread | adminclient-2] o.a.k.c.a.i.AdminMetadataManager: [AdminClient clientId=adminclient-2] Metadata update failed
org.apache.kafka.common.errors.TimeoutException: Call(callName=fetchMetadata, deadlineMs=1654177481174, tries=1, nextAllowedTryMs=1654177481275) timed out at 1654177481175 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call. Call: fetchMetadata
2022-06-02 13:44:42,876 INFO  [kafka-admin-client-thread | adminclient-3] o.a.k.c.a.i.AdminMetadataManager: [AdminClient clientId=adminclient-3] Metadata update failed
org.apache.kafka.common.errors.TimeoutException: Call(callName=fetchMetadata, deadlineMs=1654177482875, tries=1, nextAllowedTryMs=1654177482976) timed out at 1654177482876 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call. Call: fetchMetadata
2022-06-02 13:45:05,757 INFO  [kafka-admin-client-thread | adminclient-4] o.a.k.c.a.i.AdminMetadataManager: [AdminClient clientId=adminclient-4] Metadata update failed
org.apache.kafka.common.errors.TimeoutException: Call(callName=fetchMetadata, deadlineMs=1654177505756, tries=1, nextAllowedTryMs=1654177505857) timed out at 1654177505757 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call. Call: fetchMetadata
2022-06-02 13:45:05,769 INFO  [kafka-admin-client-thread | adminclient-1] o.a.k.c.a.i.AdminMetadataManager: [AdminClient clientId=adminclient-1] Metadata update failed
org.apache.kafka.common.errors.TimeoutException: Call(callName=fetchMetadata, deadlineMs=1654177505739, tries=1, nextAllowedTryMs=1654177505869) timed out at 1654177505769 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call. Call: fetchMetadata
2022-06-02 13:45:11,176 INFO  [kafka-admin-client-thread | adminclient-2] o.a.k.c.a.i.AdminMetadataManager: [AdminClient clientId=adminclient-2] Metadata update failed
org.apache.kafka.common.errors.TimeoutException: Call(callName=fetchMetadata, deadlineMs=1654177511175, tries=1, nextAllowedTryMs=1654177511276) timed out at 1654177511176 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call. Call: fetchMetadata
2022-06-02 13:45:11,205 ERROR [parallel-1] o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler: [a476e3b3-9]  500 Server Error for HTTP GET "/api/clusters/Default/brokers"
java.lang.IllegalStateException: Error while creating AdminClient for Cluster Default
at com.provectus.kafka.ui.service.AdminClientServiceImpl.lambda$createAdminClient$3(AdminClientServiceImpl.java:45)
Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
*__checkpoint ⇢ Handler com.provectus.kafka.ui.controller.BrokersController#getBrokers(String, ServerWebExchange) [DispatcherHandler]
*__checkpoint ⇢ com.provectus.kafka.ui.config.ReadOnlyModeFilter [DefaultWebFilterChain]
*__checkpoint ⇢ com.provectus.kafka.ui.config.CustomWebFilter [DefaultWebFilterChain]
*__checkpoint ⇢ org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
*__checkpoint ⇢ org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
*__checkpoint ⇢ org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain]
*__checkpoint ⇢ org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
*__checkpoint ⇢ org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
*__checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
*__checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
*__checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
*__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
*__checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
*__checkpoint ⇢ HTTP GET "/api/clusters/Default/brokers" [ExceptionHandlingWebHandler]
Original Stack Trace:`

**Comment by usmanq8** [comment] 2022-06-02 17:32
**With Kafka 2.8.0 it works** and does not work with Old version. please confirm if that is the case here.

**Comment by Haarolean** [comment] 2022-06-02 20:35
it might be, but usually we get something different (#1550) than timeouts. So I was trying to fix the timeouts/connectivity issue first. If it does work with newer versions, I'd suggest just updating your kafka, since we don't have bandwidth to support such an old version (it's about 7 years old, btw).

**Comment by usmanq8** [comment] 2022-06-03 13:21
> it might be, but usually we get something different (#1550) than timeouts. So I was trying to fix the timeouts/connectivity issue first. If it does work with newer versions, I'd suggest just updating your kafka, since we don't have bandwidth to support such an old version (it's about 7 years old, btw).

Our current version is on PROD and cannot but moved to 0.10.2.2 now. i will try out with that.
**Also provide the older version you support.**

**Comment by Haarolean** [comment] 2022-06-04 15:22
I don't have a list unfortunately, I hope anything with 2.x.x should work.
I'll close this as a duplicate of #1550.

**Closed by Haarolean** 2022-06-04 15:22 UTC
Labels: status/pending
