### ISSUE TITLE
Empty screen if try to Edit schema of proto type

### ISSUE THREAD

**Issue by agolosen** [provectus/kafka-ui#1388] opened 2022-01-13 20:19 UTC
**Describe the bug**
(A clear and concise description of what the bug is.)

There is an empty screen when you try to edit the schema of proto type.

**Set up**
(How do you run the app? 
Which version of the app are you running? Provide either docker image version or check commit hash at the top left corner. We won't be able to help you without this information.)

http://dependabot-npm-and-yarn-kafka-ui.internal.kafka-ui.provectus.io/
**Steps to Reproduce**

1. Navigate to Schema Registry 
2. Click the schema with a name containing 'proto'
3. Press the button Edit Schema
4. Observe the empty screen with the right URL (see attachment)

**Expected behavior**
(A clear and concise description of what you expected to happen)
Edit screen for the schema.
**Screenshots**
(If applicable, add screenshots to help explain your problem)

![image](https://user-images.githubusercontent.com/92585878/149402931-43117037-cb89-4716-82c2-ffef381b4f60.png)

**Additional context**
(Add any other context about the problem here)
Works correctly for other schema types.

**Comment by Haarolean** [comment] 2022-01-13 22:57
No failed backend requests

**Comment by Haarolean** [comment] 2022-01-19 10:48
A duplicate of #1188

**Closed** 2022-01-19 10:49 UTC
Labels: type/bug, status/duplicate, scope/frontend
