### ISSUE TITLE
[BE] Bug: UnsupportedVersionException: includeClusterAuthorizedOperations

### ISSUE THREAD

**Issue by fisherwei** [provectus/kafka-ui#3141] opened 2022-12-26 07:47 UTC
application.yml
```
    kafka:
      clusters:
        - name: qsmzq-prod
          bootstrapServers: node1:9092,node2:9092,node3:9092
          properties:
            security.protocol: SASL_PLAINTEXT
            sasl.mechanism: SCRAM-SHA-256
            sasl.jaas.config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="kafka" password="password";'

    spring:
      jmx:
        enabled: false
    auth:
      type: DISABLED
```

```
java.lang.IllegalStateException: Error while creating AdminClient for Cluster qsmzq-prod
	at com.provectus.kafka.ui.service.AdminClientServiceImpl.lambda$createAdminClient$3(AdminClientServiceImpl.java:45)
	at reactor.core.publisher.Mono.lambda$onErrorMap$31(Mono.java:3776)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:142)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:2063)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onError(MonoIgnoreThen.java:278)
	at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:187)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.kafka.common.errors.UnsupportedVersionException: Attempted to write a non-default includeClusterAuthorizedOperations at version 7
```

I used same config at v0.4.0, everything works as expected.

**Comment by Haarolean** [comment] 2022-12-26 08:54
@fisherwei hi, please share a full stacktrace  (you've omitted the part below)

**Comment by RoccoMathijn** [comment] 2022-12-27 15:36
Same here. Full stacktrace included, after this it just repeats.

```provectuslabs/kafka-ui:v0.5.0|c94d85724408[2661]: java.lang.IllegalStateException: Error while creating AdminClient for Cluster XXX
provectuslabs/kafka-ui:v0.5.0|c94d85724408[2661]: #011at com.provectus.kafka.ui.service.AdminClientServiceImpl.lambda$createAdminClient$3(AdminClientServiceImpl.java:45)
provectuslabs/kafka-ui:v0.5.0|c94d85724408[2661]: #011at reactor.core.publisher.Mono.lambda$onErrorMap$31(Mono.java:3776)
provectuslabs/kafka-ui:v0.5.0|c94d85724408[2661]: #011at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
provectuslabs/kafka-ui:v0.5.0|c94d85724408[2661]: #011at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:142)
provectuslabs/kafka-ui:v0.5.0|c94d85724408[2661]: #011at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134)
provectuslabs/kafka-ui:v0.5.0|c94d85724408[2661]: #011at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:2063)
provectuslabs/kafka-ui:v0.5.0|c94d85724408[2661]: #011at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
provectuslabs/kafka-ui:v0.5.0|c94d85724408[2661]: #011at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
provectuslabs/kafka-ui:v0.5.0|c94d85724408[2661]: #011at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
provectuslabs/kafka-ui:v0.5.0|c94d85724408[2661]: #011at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onError(MonoIgnoreThen.java:278)
provectuslabs/kafka-ui:v0.5.0|c94d85724408[2661]: #011at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:187)
provectuslabs/kafka-ui:v0.5.0|c94d85724408[2661]: #011at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
provectuslabs/kafka-ui:v0.5.0|c94d85724408[2661]: #011at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
provectuslabs/kafka-ui:v0.5.0|c94d85724408[2661]: #011at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
provectuslabs/kafka-ui:v0.5.0|c94d85724408[2661]: #011at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
provectuslabs/kafka-ui:v0.5.0|c94d85724408[2661]: #011at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
provectuslabs/kafka-ui:v0.5.0|c94d85724408[2661]: #011at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
provectuslabs/kafka-ui:v0.5.0|c94d85724408[2661]: #011at java.base/java.lang.Thread.run(Thread.java:833)
provectuslabs/kafka-ui:v0.5.0|c94d85724408[2661]: Caused by: org.apache.kafka.common.errors.UnsupportedVersionException: Attempted to write a non-default includeClusterAuthorizedOperations at version 5
provectuslabs/kafka-ui:v0.5.0|c94d85724408[2661]: #033[30m2022-12-27 15:18:36,575#033[0;39m #033[39mDEBUG#033[0;39m [#033[34mparallel-11#033[0;39m] #033[33mc.p.k.u.s.ClustersStatisticsScheduler#033[0;39m: Metrics updated for cluster: XXX
provectuslabs/kafka-ui:v0.5.0|c94d85724408[2661]: #033[30m2022-12-27 15:18:36,592#033[0;39m #033[34mINFO #033[0;39m [#033[34mkafka-admin-client-thread | kafka-ui-admin-client-1672153416196#033[0;39m] #033[33mo.a.k.c.NetworkClient#033[0;39m: [AdminClient clientId=kafka-ui-admin-client-1672153416196] Node 1004 
provectuslabs/kafka-ui:v0.5.0|c94d85724408[2661]: #033[30m2022-12-27 15:18:36,640#033[0;39m #033[34mINFO #033[0;39m [#033[34mkafka-admin-client-thread | kafka-ui-admin-client-1672153716196#033[0;39m] #033[33mo.a.k.c.NetworkClient#033[0;39m: [AdminClient clientId=kafka-ui-admin-client-1672153716196] Node 1 
provectuslabs/kafka-ui:v0.5.0|c94d85724408[2661]: #033[30m2022-12-27 15:18:36,697#033[0;39m #033[34mINFO #033[0;39m [#033[34mkafka-admin-client-thread | kafka-ui-admin-client-1672153116196#033[0;39m] #033[33mo.a.k.c.NetworkClient#033[0;39m: [AdminClient clientId=kafka-ui-admin-client-1672153116196] Node 1004 
provectuslabs/kafka-ui:v0.5.0|c94d85724408[2661]: #033[30m2022-12-27 15:18:36,897#033[0;39m #033[34mINFO #033[0;39m [#033[34mkafka-admin-client-thread | kafka-ui-admin-client-1672153416196#033[0;39m] #033[33mo.a.k.c.NetworkClient#033[0;39m: [AdminClient clientId=kafka-ui-admin-client-1672153416196] Node 2 
provectuslabs/kafka-ui:v0.5.0|c94d85724408[2661]: #033[30m2022-12-27 15:18:36,965#033[0;39m #033[34mINFO #033[0;39m [#033[34mkafka-admin-client-thread | kafka-ui-admin-client-1672152516196#033[0;39m] #033[33mo.a.k.c.NetworkClient#033[0;39m: [AdminClient clientId=kafka-ui-admin-client-1672152516196] Node 1002 
```

**Comment by Haarolean** [comment] 2022-12-27 19:09
Thanks. It seems like your kafka doesn't support ACLs operations we do, we'll take a look for a workaround.

**Comment by EI-Joao** [comment] 2022-12-27 20:43
I had this issue. The issue is that your kafka version does not support includeAuthorizedOperations(true). A work around is setting this to false. The downside is that the code needs to be compile again.

In this method [https://github.com/provectus/kafka-ui/blob/master/kafka-ui-api/src/main/java/com/provectus/kafka/ui/service/ReactiveAdminClient.java#L306](url) change it to false and it will work

**Comment by iliax** [comment] 2022-12-28 17:56
Hello @fisherwei  , thank you for ticket. 
Can you please check if it was fixed with `latest` tag? If so, we will add fix this to 0.5.x bugfix release.

**Comment by RoccoMathijn** [comment] 2022-12-29 09:16
I didn't open the ticket but had the same problem. `master` works for us 👍 

Thanks! 🙏

**Comment by iliax** [comment] 2022-12-29 09:24
@RoccoMathijn , thank you for confirmation

**Closed by iliax** 2022-12-29 09:24 UTC
Labels: type/bug, scope/backend, status/accepted, status/confirmed

**Comment by kewitschka** [comment] 2023-02-08 07:06
When do you plan to push an official 0.5.x patch image?

**Comment by Haarolean** [comment] 2023-02-08 10:29
@kewitschka you can pull master image for now
