### ISSUE TITLE
Authentication using SCRAM-SHA-512

### ISSUE THREAD

**Issue by KozyrevychYaroslav** [provectus/kafka-ui#3350] opened 2023-02-15 12:39 UTC
Hi @provectus-it
I need to connect to kafka servers from my work. However, I get  error `kafka-ui |org.apache.kafka.common.errors.SaslAuthenticationException: Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-512`.
My docker compose file:
```
version: '2.6'
services:

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8001:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka1
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: xxxx:9092,xxyy:9092
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: SCRAM-SHA-512
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="username" password="password";'
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION: /ca-dv.ks
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD: password
    volumes:
      - ./ssl/ca-dv.ks:/ca-dv.ks
```
 I would like to note that using the current data I can connect to the servers using the Offset Explorer UI.

**Comment by Haarolean** [comment] 2023-02-15 13:15
Hi, looks like one more case of #2116.
Do you have any special characters in your password/username?

**Comment by KozyrevychYaroslav** [comment] 2023-02-15 14:20
Yes, I do. Password has characters like  "#", "*", "$" 
Login has "_"
Server name has "-"

**Comment by Haarolean** [comment] 2023-02-21 13:45
@KozyrevychYaroslav we're currently stuck on trying to reproduce that issue on our side. Would be really great if you could provide an example (i.e. docker-compose file).

Closing this as a duplicate of #2116

**Closed by Haarolean** 2023-02-21 13:45 UTC
Labels: type/bug, status/pending

**Comment by KozyrevychYaroslav** [comment] 2023-02-22 15:36
@Haarolean I provided an example in issue https://github.com/provectus/kafka-ui/issues/2116
