### ISSUE TITLE
connect to SSL/TLS kafka broker (bootstrap server)

### ISSUE THREAD

**Issue by nemerna** [provectus/kafka-ui#1328] opened 2021-12-28 14:14 UTC
### Is your proposal related to a problem?

there is no such info in the documentation about how to connect to a secured SSL kafka broker
### Describe the solution you'd like

add support for extra envronment variables that represents keystore/truststore of the broker nodes
### Describe alternatives you've considered

(Write your answer here.)

### Additional context

if the app already supports SSL connection to kafka nodes then the you need to include that option in the documentation

**Comment by Haarolean** [comment] 2021-12-28 15:36
Hi, thanks for reaching out!

As I mentioned in the other issue, this is a duplicate of #779. The guide will be complete once we merge the corresponding PR. 
Please move to that issue if you have other questions.

**Closed by Haarolean** 2021-12-28 15:36 UTC
Labels: status/duplicate, type/enhancement
