### ISSUE TITLE
Failures when SchemaRegistry has high number of schemas defined

### ISSUE THREAD

**Issue by akamensky** [provectus/kafka-ui#887] opened 2021-09-17 03:52 UTC
**Describe the bug**

```
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | 03:38:50.833 [reactor-http-epoll-8] ERROR org.springframework.boot.autoconfigure.web.reactive.error.AbstractErrorWebExceptionHandler - [2af5bd65]  500 Server Error for HTTP GET "/api/clusters/cluster/schemas"
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | org.springframework.core.io.buffer.DataBufferLimitException: Exceeded limit on max bytes to buffer : 262144
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | 	at org.springframework.core.io.buffer.LimitedDataBufferList.raiseLimitException(LimitedDataBufferList.java:101) ~[spring-core-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | Error has been observed at the following site(s):
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | 	|_ checkpoint ⇢ Body from GET http://host1.name:8081/subjects [DefaultClientResponse]
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | 	|_ checkpoint ⇢ Handler com.provectus.kafka.ui.controller.SchemasController#getSchemas(String, ServerWebExchange) [DispatcherHandler]
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | 	|_ checkpoint ⇢ com.provectus.kafka.ui.config.ReadOnlyModeFilter [DefaultWebFilterChain]
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | 	|_ checkpoint ⇢ com.provectus.kafka.ui.config.CustomWebFilter [DefaultWebFilterChain]
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | 	|_ checkpoint ⇢ org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | 	|_ checkpoint ⇢ org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | 	|_ checkpoint ⇢ org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain]
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | 	|_ checkpoint ⇢ org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | 	|_ checkpoint ⇢ org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | 	|_ checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | 	|_ checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | 	|_ checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | 	|_ checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | 	|_ checkpoint ⇢ HTTP GET "/api/clusters/cluster/schemas" [ExceptionHandlingWebHandler]
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | Stack trace:
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | 		at org.springframework.core.io.buffer.LimitedDataBufferList.raiseLimitException(LimitedDataBufferList.java:101) ~[spring-core-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | 		at org.springframework.core.io.buffer.LimitedDataBufferList.updateCount(LimitedDataBufferList.java:94) ~[spring-core-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | 		at org.springframework.core.io.buffer.LimitedDataBufferList.add(LimitedDataBufferList.java:59) ~[spring-core-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | 		at reactor.core.publisher.MonoCollect$CollectSubscriber.onNext(MonoCollect.java:132) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | 		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | 		at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | 		at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | 		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114) [reactor-core-3.3.2.RELEASE.jar!/:3.3.2.RELEASE]
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | 		at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:218) [reactor-netty-0.9.4.RELEASE.jar!/:0.9.4.RELEASE]
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | 		at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:351) [reactor-netty-0.9.4.RELEASE.jar!/:0.9.4.RELEASE]
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | 		at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:348) [reactor-netty-0.9.4.RELEASE.jar!/:0.9.4.RELEASE]
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | 		at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:588) [reactor-netty-0.9.4.RELEASE.jar!/:0.9.4.RELEASE]
kafka_kafka-ui.1.wra5xvqg3tbz@redacted    | 		at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:90) [reactor-netty-0.9.4.RELEASE.jar!/:0.9.4.RELEASE]

```

**Set up**
Docker

**Steps to Reproduce**

1. High number of schemas (~100k)
2. Try to load

**Expected behavior**
Should work

**Comment by akamensky** [comment] 2021-09-17 05:54
Max buffer size in Spring defaults to hardcoded value of 256 KB: https://github.com/spring-projects/spring-framework/blob/main/spring-core/src/main/java/org/springframework/core/codec/AbstractDataBufferDecoder.java#L51

But what puzzles me more is why this code is using some custom HTTP queries instead of official SR client library: https://github.com/confluentinc/schema-registry/tree/master/client/src/main/java/io/confluent/kafka/schemaregistry

**Comment by germanosin** [comment] 2021-09-17 08:13
Hi, @akamensky. We are using the Reactive Web client in our schema registry service to make interaction non-blocking. 
It's default not we expected that you have so many subjects in your schema registry, and we definitely have to add pagination here. We'll do it in the next major versions. According to your problem, I think the simplest solution, for now, would be to add env variable
```
SPRING_CODEC_MAX_IN_MEMORY_SIZE: 20MB
```

**Comment by akamensky** [comment] 2021-09-17 09:24
Tried this variable, does not change anything. Still same exact error and same limit shown in error.

**Comment by akamensky** [comment] 2021-09-23 09:05
@germanosin any feedback on this issue? As I mentioned I tried env.var, but it does nothing. Still same error with the same buffer size limit.

**Comment by germanosin** [comment] 2021-09-23 11:25
@akamensky. Thanks for your partience. Trying to reproduce it.

**Comment by iliax** [comment] 2021-09-25 11:57
@akamensky, we merged https://github.com/provectus/kafka-ui/pull/903 that adds support for WebClient's buffer size tuning (now it is set to 20mb by default). Please try to use it. We will add pagination support in next releases.

**Comment by akamensky** [comment] 2021-09-27 01:21
This works now, I can browse schemas, but it is pretty bad experience -- every request is very very slow. But guess that is separate issue.

**Comment by iliax** [comment] 2021-09-27 06:43
@akamensky it is expected that it will work slow without pagination :-) if you suspect that it is caused by debug logging please try to add `-e LOGGING_LEVEL_ROOT=INFO`

**Closed** 2021-09-27 10:30 UTC
Labels: bug, backend
