### ISSUE TITLE
RBAC: Display user role(-s)

### ISSUE THREAD

**Issue by Shawcs** [provectus/kafka-ui#3760] opened 2023-05-02 09:00 UTC
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md) and the feature is not present there

### Describe the feature you're interested in

When you are logged in the UI and you have defined RBAC roles that could be useful to have the role name you are currently authenticated with.
Perhaps you can display this info in an hover fashion or when we click on the top right user login info we already have.

### Version you're running

custom build 3740

### Additional context

I know that he RBAC feature is still in development but opening that in advance

**Comment by Haarolean** [comment] 2023-05-15 12:25
A good question here is how would we display it in case the user can have multiple roles.

**Comment by Shawcs** [comment] 2023-05-15 12:29
> A good question here is how would we display it in case the user can have multiple roles.

Why not just the list of the roles name you have ?

**Comment by Haarolean** [comment] 2023-05-15 12:33
> > A good question here is how would we display it in case the user can have multiple roles.
> 
> Why not just the list of the roles name you have ?

might be a lot to display on the frontend, especially considering this would be under near "logout" button

**Comment by Haarolean** [comment] 2023-08-14 10:32
Duplicate of #3760

**Closed by Haarolean** 2023-08-14 10:32 UTC
Labels: type/enhancement, scope/backend, scope/frontend, status/accepted, status/needs-attention, status/design-review, area/rbac
