### ISSUE TITLE
SSL for kafka

### ISSUE THREAD

**Issue by JiovanMichel** [provectus/kafka-ui#1299] opened 2021-12-20 20:32 UTC
## Examples ?

I'm running Kafka UI in the docker and I want to authenticate to remote kafka. 

How to set up a secure connection? What parameters should I configure?
Kafka config properties with SASL/PLAIN.

### A basic config show erros: 

INFO [SocketServer listenerType=ZK_BROKER, nodeId=0] Failed authentication with /ip (SSL handshake failed) (org.apache.kafka.common.network.Selector)

**Comment by Haarolean** [comment] 2021-12-21 07:28
Hi, thanks for reaching out. 
Could you please try something like [this](https://github.com/provectus/kafka-ui/pull/971/files#diff-cc12ec9dc825aed8e8343c99b10c59eaa39d9b3b97953d98124c35b10441c0f8)? Though it's not merged yet this might work. Let me know how it goes.

**Comment by JiovanMichel** [comment] 2021-12-27 15:13
Thanks for the answer,
I will try.

**Comment by nemerna** [comment] 2021-12-28 15:28
hi,
i have similar issue and i tried your solution
now it really tries to connect using the certs but for now im getting the following error:
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

althought i have double checked the path is correct

in the kafka side i get the following:
2021-12-28 15:26:27,402 INFO [SocketServer brokerId=0] Failed authentication with /10.131.0.1 (SSL handshake failed) (org.apache.kafka.common.network.Selector) [data-plane-kafka-network-thread-0-ListenerName(EXTERNAL-9092)-SSL-6]


did some one was able to procced this issue

NOTE: i am using amq-streams k8s operator for running kafka

**Comment by Haarolean** [comment] 2021-12-28 15:30
@nemerna hey, thanks for the feedback. I'll take a look into this since the PR is still not merged, there's a chance it's not complete.

**Comment by Haarolean** [comment] 2021-12-28 15:33
@nemerna seems like there's a

**Comment by Haarolean** [comment] 2021-12-28 15:35
Closing as a duplicate of #779. Please move to that issue if you have other questions. The guide will be complete once we merge the corresponding PR.

**Closed by Haarolean** 2021-12-28 15:35 UTC
Labels: status/pending, type/question
