### ISSUE TITLE
UI Issue related responsive view of KSQL DB Query page

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2816] opened 2022-10-24 17:17 UTC
**Describe the bug**
Page properties are overlapping with responsive changes

**Set up**

https://www.kafka-ui.provectus.io/ui/clusters/local/ksqldb/query

**Steps to Reproduce**

1. Change the browser sizes manually

**Expected behavior**
All the components should accordingly change with responsive changes

**Screenshots**

https://user-images.githubusercontent.com/104780608/197584719-17346ee5-b963-472f-aab1-d6acedd7c1e9.mov

**Comment by Haarolean** [comment] 2022-10-25 20:20
@armenuikafka looks like a duplicate of #2721. You can double check that everything's alright now.

**Closed by Haarolean** 2022-10-25 20:20 UTC
Labels: type/bug, status/triage
