### ISSUE TITLE
Setting SERVER_SERVLET_CONTEXT_PATH causes container to crash.

### ISSUE THREAD

**Issue by ctwilleager-nt** [provectus/kafka-ui#1343] opened 2021-12-29 18:54 UTC
**Describe the bug**
Setting SERVER_SERVLET_CONTEXT_PATH causes container to crash.

**Set up**
We are attempting to use the Amazon ALB with ingress fanout in Kubernetes and trying to access Kafka UI from something like https://foo.bar/kafka-ui but setting SERVER_SERVLET_CONTEXT_PATH to "/kafka-ui" causes the container to restart continuously.

Kafka UI version: 0.3.1
Kubernetes Version: 1.20

**Steps to Reproduce**

1. Deploy Configmap containing the configuration for Kafka cluster into Kubernetes. Ensure SERVER_SERVLET_CONTEXT_PATH is set to "/kafka-ui"
2. Deploy Helm chart to Kubernetes for Kafka UI using the **existingConfigMap** to point to the deployed configmap from Step 1.
3. Pod crashes with the below exception in the logs.

**Expected behavior**
I expect the container to actually work with SERVER_SERVLET_CONTEXT_PATH set.

**Log**
Exerpt from the debug log indicating that the shutdown hook is being called for some unknown reason:
`2021-12-29 18:45:37,853 DEBUG [SpringApplicationShutdownHook] o.s.b.a.ApplicationAvailabilityBean: Application availability state ReadinessState changed from ACCEPTING_TRAFFIC to REFUSING_TRAFFIC
2021-12-29 18:45:37,861 DEBUG [SpringApplicationShutdownHook] o.s.b.w.r.c.AnnotationConfigReactiveWebServerApplicationContext: Closing org.springframework.boot.web.reactive.context.AnnotationConfigReactiveWebServerApplicationContext@4466af20, started on Wed Dec 29 18:43:11 GMT 2021
2021-12-29 18:45:37,862 DEBUG [SpringApplicationShutdownHook] o.s.c.s.DefaultLifecycleProcessor: Stopping beans in phase 2147483647
2021-12-29 18:45:37,863 DEBUG [SpringApplicationShutdownHook] o.s.c.s.DefaultLifecycleProcessor: Bean 'webServerGracefulShutdown' completed its stop procedure
2021-12-29 18:45:37,863 DEBUG [SpringApplicationShutdownHook] o.s.c.s.DefaultLifecycleProcessor: Stopping beans in phase 2147483646
2021-12-29 18:45:37,867 DEBUG [SpringApplicationShutdownHook] o.s.c.s.DefaultLifecycleProcessor: Bean 'webServerStartStop' completed its stop procedure
2021-12-29 18:45:37,867 DEBUG [SpringApplicationShutdownHook] o.s.s.c.ThreadPoolTaskScheduler: Shutting down ExecutorService 'taskScheduler'
2021-12-29 18:45:37,867 DEBUG [SpringApplicationShutdownHook] o.s.j.e.MBeanExporter: Unregistering JMX-exposed beans on shutdown
2021-12-29 18:45:37,871 DEBUG [SpringApplicationShutdownHook] o.a.k.c.a.KafkaAdminClient: [AdminClient clientId=adminclient-1] Initiating close operation.
2021-12-29 18:45:37,871 DEBUG [SpringApplicationShutdownHook] o.a.k.c.a.KafkaAdminClient: [AdminClient clientId=adminclient-1] Waiting for the I/O thread to exit. Hard shutdown in 31536000000 ms.
2021-12-29 18:45:37,875 ERROR [scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler: Unexpected error occurred in scheduled task
reactor.core.Exceptions$ReactiveException: java.lang.InterruptedException
	at reactor.core.Exceptions.propagate(Exceptions.java:392)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:91)
	at reactor.core.publisher.Mono.block(Mono.java:1706)
	at com.provectus.kafka.ui.service.ClustersMetricsScheduler.updateMetrics(ClustersMetricsScheduler.java:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.InterruptedException: null
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1040)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1345)
	at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:87)
	... 14 common frames omitted
`
**Additional Information**
Removing SERVER_SERVLET_CONTEXT_PATH from the configuration causes the pod to come up, but since our ingress is defined to use a fanout URL, the page returned when access the UI is always blank. Inspecting the page shows that all of the assets called to load the UI are returning 404 because the fanout path is not being respected by the underlying pod.

**Comment by Haarolean** [comment] 2021-12-29 19:13
Hi, thanks for reaching out.
I couldn't reproduce this with simple docker-compose setup.
Could you please share the full pod log from start to end of one restart lifecycle?

**Comment by ctwilleager-nt** [comment] 2021-12-29 19:29
Attached is the full lifecycle log of the pod when SERVER_SERVLET_CONTEXT_PATH is set to "/kafka-ui".

[kafka-ui-fail.log](https://github.com/provectus/kafka-ui/files/7790329/kafka-ui-fail.log)

**Comment by Haarolean** [comment] 2021-12-30 15:39
@ctwilleager-nt 
Since you're providing a custom configmap, the value is not respected in liveness and readiness probes which cause the restarts.
We suppose you have to pass `SERVER_SERVLET_CONTEXT_PATH` explicitly in [values.yaml](https://github.com/provectus/kafka-ui/blob/master/charts/kafka-ui/values.yaml#L27). 
If that doesn't help, let us know.

**Comment by ctwilleager-nt** [comment] 2021-12-30 17:46
Setting it directly in values.yaml does keep the pod running. Now we've gone from pod crashing to just getting a flat 404 whenever we try to open the UI. So it's progress...of a kind anyway.

**Comment by ctwilleager-nt** [comment] 2021-12-30 19:07
This is the full error we get causing the 404:

`{"code":5000,"message":"404 NOT_FOUND","timestamp":1640891014551,"requestId":"4cbaed95-2, L:/127.0.0.1:8080 - R:/127.0.0.1:54742","fieldsErrors":null,"stackTrace":"org.springframework.web.server.ResponseStatusException: 404 NOT_FOUND
at org.springframework.web.reactive.resource.ResourceWebHandler.lambda$handle$1(ResourceWebHandler.java:379)
Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: \nError has been observed at the following site(s):
*__checkpoint ⇢ com.provectus.kafka.ui.config.CustomWebFilter [DefaultWebFilterChain]
*__checkpoint ⇢ com.provectus.kafka.ui.config.ReadOnlyModeFilter [DefaultWebFilterChain]
*__checkpoint ⇢ org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
*__checkpoint ⇢ org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
*__checkpoint ⇢ org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain]
*__checkpoint ⇢ org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
*__checkpoint ⇢ org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
*__checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
*__checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
*__checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
*__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
*__checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
*__checkpoint ⇢ HTTP GET \"/kafka-ui\" [ExceptionHandlingWebHandler]\nStack trace:
at org.springframework.web.reactive.resource.ResourceWebHandler.lambda$handle$1(ResourceWebHandler.java:379)
at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
at reactor.core.publisher.Mono.subscribe(Mono.java:4399)
at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82)
at reactor.core.publisher.Operators.complete(Operators.java:137)
at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46)
at reactor.core.publisher.Mono.subscribe(Mono.java:4399)
at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:255)
at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:282)
at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:861)
at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398)
at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:169)
at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2194)
at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2068)
at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96)
at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
at reactor.core.publisher.Mono.subscribe(Mono.java:4399)
at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:449)
at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:219)
at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:165)
at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:87)
at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
at reactor.core.publisher.Mono.subscribe(Mono.java:4399)
at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82)
at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onComplete(MonoPeekTerminal.java:299)
at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onComplete(MonoPeekTerminal.java:299)
at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:148)
at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:113)
at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:101)
at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:282)
at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:861)
at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:118)
at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398)
at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.request(FluxFilterFuseable.java:191)
at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:169)
at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:110)
at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96)
at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onSubscribe(FluxFilterFuseable.java:87)
at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
at reactor.core.publisher.Mono.subscribe(Mono.java:4399)
at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:449)
at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:219)
at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:165)
at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:87)
at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
at reactor.core.publisher.Mono.subscribe(Mono.java:4399)
at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:255)
at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
at reactor.core.publisher.Mono.subscribe(Mono.java:4399)
at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82)
at reactor.core.publisher.FluxFilter$FilterSubscriber.onComplete(FluxFilter.java:166)
at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onComplete(FluxPeekFuseable.java:940)
at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:85)
at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2400)
at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2194)
at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2068)
at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
at reactor.core.publisher.Mono.subscribe(Mono.java:4399)
at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82)
at reactor.core.publisher.MonoNext$NextSubscriber.onComplete(MonoNext.java:102)
at reactor.core.publisher.FluxFilter$FilterSubscriber.onComplete(FluxFilter.java:166)
at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:846)
at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:608)
at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:588)
at reactor.core.publisher.FluxFlatMap$FlatMapMain.onComplete(FluxFlatMap.java:465)
at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onComplete(FluxPeekFuseable.java:277)
at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:294)
at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:230)
at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:144)
at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371)
at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:178)
at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:165)
at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:87)
at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onComplete(FluxDefaultIfEmpty.java:109)
at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:142)
at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:142)
at reactor.core.publisher.FluxFilter$FilterSubscriber.onComplete(FluxFilter.java:166)
at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:269)
at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1817)
at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:337)
at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:354)
at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200)
at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200)
at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:181)
at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)\n"}`

**Comment by Haarolean** [comment] 2021-12-30 19:11
Have you tried adding a trailing slash at the end of the URL?

**Comment by ctwilleager-nt** [comment] 2021-12-30 19:16
@Haarolean Yeah I've tried that. Both in the browser and also adding it to the SERVER_SERVLET_CONTEXT_PATH variable. Neither scenario works.

**Comment by Haarolean** [comment] 2021-12-30 19:19
Can you reach /<context>/actuator/info manually? Does it show a JSON with HTTP 200?

**Comment by ctwilleager-nt** [comment] 2021-12-30 19:35
Yes I can reach the /kafka-ui/actuator/info manually.

**Comment by Haarolean** [comment] 2021-12-30 19:36
But /kafka-ui/ doesn’t work, right?

**Comment by ctwilleager-nt** [comment] 2021-12-30 20:01
@Haarolean Correct, using /kafka-ui/ doesn't work. It just returns the pod to the state of constantly dying because the liveness probe attempts to access the actuator health endpoint as /kafka-ui//actuator/info and gets a 404 not found.

**Comment by Haarolean** [comment] 2021-12-30 20:44
Wait, so you can reach the health endpoint manually but it doesn't work as a liveness probe?

**Comment by ctwilleager-nt** [comment] 2021-12-30 21:14
@Haarolean No, I can reach the health endpoint with /kafka-ui as the context. None of it works with /kafka-ui/ (trailing slash) and the pod dies due to liveness probe failure..

**Comment by Haarolean** [comment] 2021-12-30 21:29
Okay, so if you set up `/kafka-ui` as the context, can you reach the app in browser via `/kafka-ui/`?:)

**Comment by ctwilleager-nt** [comment] 2021-12-30 21:38
@Haarolean It does not work that way. While the actuator endpoint works, when attempting to access the actual UI, I get the above error I posted above: 
https://github.com/provectus/kafka-ui/issues/1343#issuecomment-1003149430

So the UI does not work when using a context path. Only the health check endpoint does.

**Comment by Haarolean** [comment] 2021-12-30 21:51
That's really weird ☹️ We'll try to get a working env with a custom context path and I'll get back to you

**Comment by Haarolean** [comment] 2022-01-11 12:33
It works on our end.
This is a helm config we used:

configmap:
```
KAFKA_CLUSTERS_0_NAME: "local"
KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "ribragimov1-cp-kafka:9092"
KAFKA_CLUSTERS_0_SCHEMAREGISTRY: "http://ribragimov1-cp-schema-registry:8081"
KAFKA_CLUSTERS_0_ZOOKEEPER: "ribragimov1-cp-zookeeper:2181"
KAFKA_CLUSTERS_0_KSQLDBSERVER: "http://ribragimov1-cp-ksql-server:8088"
KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: "local"
KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: "http://ribragimov1-cp-kafka-connect:8083"
AUTH_TYPE: "LOGIN_FORM"
SPRING_SECURITY_USER_NAME: "redacted"
SPRING_SECURITY_USER_PASSWORD: "redacted"
MANAGEMENT_HEALTH_LDAP_ENABLED: "FALSE"
SERVER_SERVLET_CONTEXT_PATH: "/kafka-ui"
```

ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ribragimov1-kafka-ui
  annotations:
spec:
  ingressClassName: nginx
  rules:
    - host: ribragimov1.kafka-ui.provectus.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "ribragimov1-kafka-ui"
                port:
                  number: 80
```

Which worked perfectly fine on `http://xxx.yyy/kafka-ui/`.

I'm closing this since this is clearly not a bug. Feel free to join us in discussions or on discord!

**Closed by Haarolean** 2022-01-11 12:33 UTC
Labels: type/bug, status/accepted, status/on-hold, helm

**Comment by elainemielas** [comment] 2023-08-16 11:51
Hi, I actually ran into similar issue, deploying with helm to AKS.

`yamlApplicationConfig:
  server.servlet.context.path: /kafka-ui
  kafka:
    clusters:
      - name: name
        readonly: true
        bootstrapServers: .azure.confluent.cloud:9092
        properties:
            security.protocol: SASL_SSL
            sasl.mechanism: PLAIN
            ssl.endpoint.identification.algorithm: https
            sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="" password="";
  management:
    health:
      ldap:
        enabled: false

ingress:
  enabled: true
  annotations:
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: ""
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
  ingressClassName: "azure-application-gateway"
  path: "/"
  pathType: "Prefix"  
  host: ""
  tls:
    enabled: false
    secretName: ""
  precedingPaths: []
  succeedingPaths: []`

no crashes, the app works perfectly fine at domain/, but not on domain/kafka-ui (404), domain/kafka-ui/actuator/info works, domain/actuator/info gives 404 again.

Startup message:
Starting KafkaUiApplication using Java 17.0.6 with PID 1 (/kafka-ui-api.jar started by kafkaui in /)

Tried to set this parameter as env var as well, with the same result.
Let me know if you need more info/logs, here's full discussion on discord: https://discord.com/channels/897805035122077716/897805035122077719/1141297630987702282
