### ISSUE TITLE
Unresponsive search field in Topics - Specific Topic - Messages tab

### ISSUE THREAD

**Issue by Khakha-A** [provectus/kafka-ui#1226] opened 2021-12-10 11:34 UTC
**Describe the bug**
The search field available in the Messages tab of any specific Topic seems not to work. It doesn't search anything.

**Set up**
http://redesign.internal.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Go to Topics - Select "Test_Part6" topic - Messages tab
2. Type anything in the Search field - sorting/searching doesn't work

**Expected behavior**
The list of messages is changed based on input in the field

**Screenshots**
![image](https://user-images.githubusercontent.com/39586798/145567955-b6f1c6c4-0029-4a8a-adb4-46af9eed805c.png)

**Additional context**
Maybe the problem is related to and caused by the contents of the produced messages.

**Comment by workshur** [comment] 2021-12-21 18:54
The search query is applied by pressing the submit button

**Comment by Haarolean** [comment] 2022-01-25 10:17
Duplicate of #1242

**Closed by Haarolean** 2022-01-25 10:17 UTC
Labels: type/bug, scope/frontend, status/accepted, status/confirmed, redesign, status/needs-attention
