### ISSUE TITLE
Can't see topic and broker information in GUI

### ISSUE THREAD

**Issue by sarlindo** [provectus/kafka-ui#1659] opened 2022-02-22 14:28 UTC
**Describe the bug**

I seem to be having an issue seeing my kafka broker and topic information in the GUI. I can see consumers and then drill down and see topics, but can't seem to see topics and/or broker info in the GUI?

**Set up**
I am testing the app via your docker image and running the command below:

docker run -p 8080:8080 -e KAFKA_CLUSTERS_0_NAME=sit1 -e KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=XXXX:PORT -e KAFKA_CLUSTERS_0_ZOOKEEPER=XXXX:PORT -e KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS=XXXX:PORT -e KAFKA_CLUSTERS_0_READONLY=true -d provectuslabs/kafka-ui:latest

**Steps to Reproduce**

1.  run docker image and connect to kafka cluster

**Expected behavior**

For me to be able to see the broker and topic information by clicking on the left hand side of the GUI screen under broker and/or topic information.

I can see the consumer information just fine and i'm able to drill into topics etc...

**Screenshots**
![broker-screen](https://user-images.githubusercontent.com/56277508/155152574-551664a7-69b3-4705-afc5-e0680416c775.png)

![consumer-screen-works](https://user-images.githubusercontent.com/56277508/155153323-a5211067-3b9a-4b1f-be17-5d866072cbcf.png)

**Additional context**

**Comment by Haarolean** [comment] 2022-02-22 15:22
Hi, please share which failed requests you have (if any) in browser's developer console.
And your container logs, there might be some stacktraces.

**Comment by sarlindo** [comment] 2022-02-22 16:35
There are no failed requests in browser.

Container logs attached below:
[docker.log](https://github.com/provectus/kafka-ui/files/8118401/docker.log)

**Comment by Haarolean** [comment] 2022-02-22 16:42
Yeah, this message:
`org.apache.kafka.common.errors.UnsupportedVersionException: Attempted to write a non-default includeSynonyms at version 0`
says your cluster version may be outdated. Which version is that?

**Comment by sarlindo** [comment] 2022-02-22 19:09
very old version 0.11.0.0.

We are upgrading it very soon and will retest against newer version of Kafka. Thanks.

**Comment by sarlindo** [comment] 2022-02-22 22:42
@Haarolean ok i tested it against a newer version of kafka and it's working and will close very soon. I have one last question. Does this ENV variable KAFKA_CLUSTERS_0_READONLY=true ensure that the GUI can only be used for readonly and no updates like adding new topics, clearing messages etc.. is allow? Is that correct?

**Comment by Haarolean** [comment] 2022-02-22 22:48
@sarlindo that's great it works.
Yes, readonly mode will allow just GET requests to any endpoint.

**Comment by Haarolean** [comment] 2022-02-22 22:49
duplicate of #1550

**Closed by Haarolean** 2022-02-22 22:48 UTC
Labels: type/bug, status/pending, status/triage
