### ISSUE TITLE
Add audit logging for tracing user activities

### ISSUE THREAD

**Issue by smahroug** [provectus/kafka-ui#3996] opened 2023-06-30 15:47 UTC
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?
Managing  Kafka Cluster using Kafka UI

### Describe the feature you're interested in

We are using Kafka UI for some months. We would like to trace the activity of Kafka UI users in a separate log file ( example: audit.log), or even save it in a specific Kafka topic ( internal topic with long default retention (3 months? )  
In this file, we could like to see all the actions made by a user with some details ( date, user, actions ...): create a topic, edit topic configuration, view data in a topic, delete messages from a topic, update schemas, and so on.

### Version you're running

0.7.0

**Comment by Haarolean** [comment] 2023-06-30 22:39
duplicate of #2998

**Closed by Haarolean** 2023-06-30 22:39 UTC
Labels: status/triage, type/feature
