### ISSUE TITLE
Add "Preview" for Messages Key and Content

### ISSUE THREAD

**Issue by armenuikafka** [provectus/kafka-ui#2543] opened 2022-09-08 03:33 UTC
**Describe the bug**

Add "Preview" for Messages Key and Content

**Set up**
https://www.kafka-ui.provectus.io/

**Steps to Reproduce**

1. Navigate to Topic's profile
2. Turn to Messages tab

**Expected behavior**
Should be available "Preview" for each Message Kay and Content

**Screenshots**
<img width="1437" alt="preview" src="https://user-images.githubusercontent.com/104780608/189028185-53019c45-9a80-484e-85fb-ed2a166fd4f7.png">

**Additional context**

**Comment by Haarolean** [comment] 2022-09-12 15:02
Duplicate of #2544

**Closed by Haarolean** 2022-09-12 15:02 UTC
Labels: type/bug, status/triage
