### ISSUE TITLE
[Feature] button to copy content of message

### ISSUE THREAD

**Issue by jcpunk** [provectus/kafka-ui#4108] opened 2023-08-10 17:55 UTC
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

When working with large messages, complex keys, or messy headers, it is nice to copy them out into external locations for further analysis.

### Describe the feature you're interested in

Add a button next to the text box container Key/Value/Header that will copy the content of the box.

### Describe alternatives you've considered

Manual mouse selection of box

### Version you're running

56fa824

### Additional context

Something similar to the github copy button would be idea.

**Comment by Haarolean** [comment] 2023-08-25 09:05
duplicate of #597
please upvote the original issue

**Closed by Haarolean** 2023-08-25 09:05 UTC
Labels: status/triage, type/feature
