### ISSUE TITLE
Support RedPanda

### ISSUE THREAD

**Issue by moming00** [provectus/kafka-ui#3393] opened 2023-02-23 06:20 UTC
### Which version of the app are you running?
v0.5.0
(
[027d9b4](https://github.com/provectus/kafka-ui/commit/027d9b4)
)

### Is your proposal related to a problem?

docker run -p 8080:8080 -e KAFKA_CLUSTERS_0_NAME=local -e KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=192.168.110.10:19092,192.168.110.14:19092,192.168.110.6:19092 -d provectuslabs/kafka-ui:latest
redpanda failed to show me the broker list and topic list

Here is docker logs:
[log.txt](https://github.com/provectus/kafka-ui/files/10810796/log.txt)

**Comment by Haarolean** [comment] 2023-02-23 08:18
Hi, please use `provectuslabs/kafka-ui:master` instead.

Closing as a duplicate of #3174 & #3141.

**Closed by Haarolean** 2023-02-23 08:18 UTC
Labels: status/triage, type/feature

**Comment by Haarolean** [comment] 2023-02-23 08:39
@moming00 let me know if it helps

**Comment by moming00** [comment] 2023-02-23 08:41
> @moming00 let me know if it helps

sorry fogot to mention, it works smoothly.
